//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDoors.Models
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel;
  using System.Web.Mvc;
    
    public partial class ArchiveConfig
    {
        public int id { get; set; }
        public string Name { get; set; }
        [AllowHtml]
        public string ODNote { get; set; }
        public string BookmarksNote { get; set; }

        public bool SendEmail { get; set; }
        [DisplayName("Post as drafts")]
        public bool PostWorks { get; set; }
        public int ItemsPerPage { get; set; }
        public string Key { get; set; }
        public string Archivist { get; set; }
        public string CollectionName { get; set; }
        public int Imported { get; set; }
        public int NotImported { get; set; }
    }
}
