//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDoors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Stories = new HashSet<Story>();
            this.Bookmarks = new HashSet<Bookmark>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public bool Imported { get; set; }
        public bool DoNotImport { get; set; }
    
        public virtual ICollection<Story> Stories { get; set; }
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
    }
}
