//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDoors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public int AuthorID { get; set; }
        public string Rating { get; set; }
        public System.DateTime Date { get; set; }
        public string Tags { get; set; }
        public string Warnings { get; set; }
        public string Notes { get; set; }
        public string Url { get; set; }
        public bool Imported { get; set; }
        public bool DoNotImport { get; set; }
        public string Ao3Url { get; set; }
        public string Fandoms { get; set; }
        public string Characters { get; set; }
        public string Relationships { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
